// import React from 'react';
// import { Inter } from 'next/font/google';
// import { Metadata } from 'next';

// import './globals.css';
// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Transcode Solution',
//   description: 'Generated by Transcode Solution',
//   // icons: {
//   //   icon: 'https://casestudy.transcodesolution.com/',
//   // },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         {/* Additional Head Content */}
//       </head>
//       <body className={inter.className}>
//         <header>
//           <Navbar />
//         </header>
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }


"use client";
import React from 'react';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';

import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Additional Head Content */}
      </head>
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
